server:
  port: 31001
spring:
  application:
    name: yh-service-manage-cms
  data:
    mongodb:
      uri: mongodb://root:admin@localhost:27017/
      database: yh_cms
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    port: 5672
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848