server:
  port: 31000
spring:
  application:
    name: yh-service-manage-cms-handler
  data:
    mongodb:
      uri: mongodb://root:admin@localhost:27017/
      database: yh_cms
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    port: 5672
yh:
  mq:
    #客户端监控的队列名称（不同的客户端监控的队列不能重复）
    queue: cms_course_post_queue_02
    #此routingKey为门户站点ID
    routeKey: 63476b56d21f533a54fb233e